#+TITLE: Comentários sobre dados de atração de caso em Heródoto: pressuposição e variação de manuscritos
#+AUTHOR: Caio Borges Aguida Geraldes

* Herodotus
** δοκεῖ

Há a repetição de πέμψαντ- de 1.2.3, mas a ação de enviar parece mais formular do que pressuposta.

8. Herodotus - Historiae - 1 3
Οὕτω δὴ ἁρπάσαντος αὐτοῦ Ἑλένην, τοῖσι Ἕλλησι δόξαι πρῶτον πέμψαντας ἀγγέλους ἀπαιτέειν τε Ἑλένην καὶ δίκας τῆς ἁρπαγῆς αἰτέειν.

Repetição de πέμπω, dá para aceitar que é uma pressuposição, embora bem próximo.

9. Herodotus - Historiae - 1 19
Μακροτέρης δέ οἱ γινομένης τῆς νούσου, πέμπει ἐς Δελφοὺς θεοπρόπους, εἴτε δὴ συμβουλεύσαντός τεο, εἴτε καὶ αὐτῷ ἔδοξε πέμψαντα τὸν θεὸν ἐπειρέσθαι περὶ τῆς νούσου.

Certamente διαβάντας é anafórico, se é pressuposto é difícil dizer.

10. Herodotus - Historiae - 1 207
Νῦν ὦν μοι δοκέει διαβάντας προελθεῖν ὅσον ἂν ἐκεῖνοι ὑπεξίωσι, ἐνθεῦτεν δὲ τάδε ποιεῦντας πειρᾶσθαι ἐκείνων περιγενέσθαι (...) % τούτοισι ὦν τοῖσι ἀνδράσι τῶν προβάτων ἀφειδέως πολλὰ κατακόψαντας καὶ σκευάσαντας προθεῖναι ἐν τῷ στρατοπέδῳ τῷ ἡμετέρῳ δαῖτα, πρὸς δὲ καὶ κρητῆρας ἀφειδέως οἴνου ἀκρήτου καὶ σιτία παντοῖα.

Sem condições.

11. Herodotus - Historiae - 2 151
ἐς δὲ τὰ ἕλεα ἔδοξέ σφι διῶξαι ψιλώσαντας τὰ πλεῖστα τῆς δυνάμιος, ἐκ δὲ τῶν ἑλέων ὁρμώμενον μὴ ἐπιμίσγεσθαι τῇ ἄλλῃ Αἰγύπτῳ.


μεταδιώξαντας é parte essencial do conselho de Prexaspes a Cambises, não há como ser pressuposto. A variação nos manuscritos são absurdas, nem vale comentar, um genitivo sem sentido e um particípio futuro, certamente treta de transmissão.

12. Herodotus - Historiae - 3 62
Νῦν ὦν μοι δοκέει μεταδιώξαντας τὸν κήρυκα ἐξετάζειν εἰρωτῶντας παρ' ὅτεο ἥκων προαγορεύει ἡμῖν Σμέρδιος βασιλέος ἀκούειν.


Nova informação apresentada por λαβόντα. A variante λαβόντας é atestada (A), mas muito improvável junto a ἕκαστον (omitido em d).

13. Herodotus - Historiae - 4 3
Νῦν ὦν μοι δοκέει αἰχμὰς μὲν καὶ τόξα μετεῖναι, λαβόντα δὲ ἕκαστον τοῦ ἵππου τὴν μάστιγα ἰέναι ἆσσον αὐτῶν.


Informação nova. Há uma proposta de Cobet para substituir λογισαμένους por λογισαμένοις (talvez -οισι?).

14. Herodotus - Historiae - 4 11
τοῖσι δὲ βασιλεῦσι δόξαι ἐν τῇ ἑωυτῶν κεῖσθαι ἀποθανόντας μηδὲ συμφεύγειν τῷ δήμῳ, λογισαμένους ὅσα τε ἀγαθὰ πεπόνθασι καὶ ὅσα φεύγοντας ἐκ τῆς πατρίδος κακὰ ἐπίδοξα καταλαμβάνειν.


Há o pressuposto de que o memorial foi feito e deixado onde foi deixado. Há variação no manuscrito d, mas para o nominativo, o que é inesperado e difícil de justificar no contexto.

15. Herodotus - Historiae - 4 81
Κομισθῆναί τε δὴ χρῆμα πολλὸν ἀρδίων καί οἱ δόξαι ἐξ αὐτέων μνημόσυνον ποιήσαντι λιπέσθαι· ἐκ τουτέων δέ μιν τὸ χαλκήιον ποιῆσαι τοῦτο καὶ ἀναθεῖναι ἐς τὸν Ἐξαμπαῖον τοῦτον.

Informação nova, variantes inesperadas no manuscrito D.

16. Herodotus - Historiae - 4 134
Νῦν ὦν μοι δοκέει, ἐπεὰν τάχιστα νὺξ ἐπέλθῃ, ἐκκαύσαντας τὰ πυρὰ ὡς ἐώθαμεν καὶ ἄλλοτε ποιέειν, τῶν στρατιωτέων τοὺς ἀσθενεστάτους ἐς τὰς ταλαιπωρίας ἐξαπατήσαντας καὶ τοὺς ὄνους πάντας καταδήσαντας ἀπαλλάσσεσθαι, πρὶν ἢ καὶ ἐπὶ τὸν Ἴστρον ἰθῦσαι Σκύθας λύσοντας τὴν γέφυραν ἢ καί τι Ἴωσι δόξαι τὸ ἡμέας οἷόν τε ἔσται ἐξεργάσασθαι.
Informação nova.

17. Herodotus - Historiae - 5 92 c
ἐς ὃ δή σφι χρόνου ἐγγινομένου ἔδοξε αὖτις παρελθόντας πάντας τοῦ φόνου μετίσχειν.


Informação nova.

18. Herodotus - Historiae - 5 96
οὐκ ἐνδεκομένοισι δέ σφι ἐδέδοκτο ἐκ τοῦ φανεροῦ τοῖσι Πέρσῃσι πολεμίους εἶναι.


Informação nova.

19. Herodotus - Historiae - 6 22
ἐδόκεε δὲ μετὰ τὴν ναυμαχίην αὐτίκα βουλευομένοισι, πρὶν ἤ σφι ἐς τὴν χώρην ἀπικέσθαι τὸν τύραννον Αἰάκεα, ἐς ἀποικίην ἐκπλέειν μηδὲ μένοντας Μήδοισί τε καὶ Αἰάκεϊ δουλεύειν.


Informação nova.

20. Herodotus - Historiae - 9 25
ἐς τοῦτον δὴ τὸν χῶρον καὶ ἐπὶ τὴν κρήνην τὴν Γαργαφίην τὴν ἐν τῷ χώρῳ τούτῳ ἐοῦσαν ἔδοξέ σφι χρεὸν εἶναι ἀπικέσθαι καὶ διαταχθέντας στρατοπεδεύεσθαι.


Informação nova.

21. Herodotus - Historiae - 9 60
Νῦν ὦν δέδοκται τὸ ἐνθεῦτεν τὸ ποιητέον ἡμῖν, ἀμυνομένους γὰρ τῇ δυνάμεθα ἄριστα περιστέλλειν ἀλλήλους.


Informação pressuposta.

22. Herodotus - Historiae - 9 87
Ἄνδρες Θηβαῖοι, ἐπειδὴ οὕτω δέδοκται τοῖσι Ἕλλησι, μὴ πρότερον ἀπαναστῆναι πολιορκέοντας ἢ ἐξέλωσι Θήβας ἢ ἡμέας αὐτοῖσι παραδῶτε (...)


Informação nova.

23. Herodotus - Historiae - 9 106
Πρὸς ταῦτα Πελοποννησίων μὲν τοῖσι ἐν τέλεϊ ἐοῦσι ἐδόκεε τῶν μηδισάντων ἐθνέων τῶν Ἑλληνικῶν τὰ ἔπιπλα ἐξαναστήσαντας δοῦναι τὴν χώρην Ἴωσι ἐνοικῆσαι·


Informação nova.

24. Herodotus - Historiae - 9 114
Τοῖσι μέν νυν ἀμφὶ Λευτυχίδην Πελοποννησίοισι ἔδοξε ἀποπλέειν ἐς τὴν Ἑλλάδα, Ἀθηναίοισι δὲ καὶ Ξανθίππῳ τῷ στρατηγῷ αὐτοῦ ὑπομείναντας πειρᾶσθαι τῆς Χερσονήσου.

Informação nova.

124. Herodotus - Historiae - 6 86 a
ταῦτά τε ὦν ἐπιλεγομένῳ καὶ βουλευομένῳ ἔδοξέ μοι τὰ ἡμίσεα πάσης τῆς οὐσίης ἐξαργυρώσαντα θέσθαι παρὰ σέ, εὖ ἐξεπισταμένῳ ὥς μοι κείμενα ἔσται παρὰ σοὶ σόα.

** δέομαι

Os tebanos discutem a interpretação do oráculo e entendem que o povo "mais próximo" seriam seus vizinhos. Um deles no entanto levanta a possibilidade de serem os Eginetas que eram "cunhados" por casamento das filhas de Esopo, logo eles seriam mais aptos a ajudar (do que os vizinhos).

2. Herodotus - Historiae - 5 80
τουτέων ἀδελφεῶν ἐουσέων δοκέω ἡμῖν Αἰγινητέων δέεσθαι τὸν θεὸν χρῆσαι τιμωρητήρων γενέσθαι.


Nothing make us believe that this state of affairs is pressuposed.

3. Herodotus - Historiae - 6 100
Ἐρετριέες δὲ πυνθανόμενοι τὴν στρατιὴν τὴν Περσικὴν ἐπὶ σφέας ἐπιπλέουσαν Ἀθηναίων ἐδεήθησαν σφίσι βοηθοὺς γενέσθαι.

** ἐντέλλομαι

Informação nova, sem variação.

48. Herodotus - Historiae - 1 47
Ἐντειλάμενος δὲ τοῖσι Λυδοῖσι τάδε ἀπέπεμπε ἐς τὴν διάπειραν τῶν χρηστηρίων, ἀπ' ἧς ἂν ἡμέρης ὁρμηθέωσι ἐκ Σαρδίων, ἀπὸ ταύτης ἡμερολογέοντας τὸν λοιπὸν χρόνον ἑκατοστῇ ἡμέρῃ χρᾶσθαι τοῖσι χρηστηρίοισι, ἐπειρωτῶντας «ὅ τι ποιέων τυγχάνοι ὁ Λυδῶν βασιλεὺς Κροῖσος ὁ Ἀλυάττεω»·


Poderíamos dizer que há uma pressuposição aqui: quando é enunciado que Harpago escondeu uma carta a Ciro dentro de uma lebre, espera-se que essa lebre seja dada (διδόντα) a Ciro. No entanto não há peso anafórico claro e discursivamente a informação é nova para os mensageiros.

49. Herodotus - Historiae - 1 123
ἐντειλάμενός οἱ ἀπὸ γλώσσης διδόντα τὸν λαγὸν Κύρῳ ἐπειπεῖν αὐτοχειρίῃ μιν διελεῖν καὶ μηδένα οἱ ταῦτα ποιεῦντι παρεῖναι.


Informação nova.

50. Herodotus - Historiae - 2 121 c
Ἀπορεόμενον δέ μιν τάδε ποιῆσαι· τοῦ φωρὸς τὸν νέκυν κατὰ τοῦ τείχεος κατακρεμάσαι, φυλάκους δὲ αὐτοῦ καταστήσαντα ἐντείλασθαί σφι, τὸν ἂν ἴδωνται ἀποκλαύσαντα ἢ κατοικτισάμενον, συλλαβόντας ἄγειν πρὸς ἑωυτόν.


A única variação atestada é a falta de ἐκ- no particípio: ἀνδροποδισαμένους (d). Informação nova.

51. Herodotus - Historiae - 3 25
καὶ τούτοισι μὲν ἐνετέλλετο Ἀμμωνίους ἐξανδραποδισαμένους τὸ χρηστήριον τὸ τοῦ Διὸς ἐμπρῆσαι,


Informação nova.

52. Herodotus - Historiae - 3 135
Ἐπείτε γὰρ τάχιστα ἡμέρη ἐπέλαμψε, καλέσας Περσέων ἄνδρας δοκίμους πεντεκαίδεκα ἐνετέλλετό σφι ἑπομένους Δημοκήδεϊ διεξελθεῖν τὰ παραθαλάσσια τῆς Ἑλλάδος, ὅκως τε μὴ διαδρήσεταί σφεας ὁ Δημοκήδης, ἀλλά μιν πάντως ὀπίσω ἀπάξουσι.


Informação nova, embora tanto o leitor quanto interlocutor saibam que as pessoas estão guardando a ponte. O foco no entanto está no período. Anotando como falso.

53. Herodotus - Historiae - 4 133
Πυνθανόμεθα γὰρ Δαρεῖον ἐντείλασθαι ὑμῖν ἑξήκοντα ἡμέρας μούνας φρουρήσαντας τὴν γέφυραν, αὐτοῦ μὴ παραγενομένου ἐν τούτῳ τῷ χρόνῳ, ἀπαλλάσσεσθαι ἐς τὴν ὑμετέρην.


Informação nova.

54. Herodotus - Historiae - 5 12
Τελεωθέντων δὲ ἀμφοτέροισι οὗτοι μὲν κατὰ εἵλοντο ἐτράποντο, Δαρεῖον δὲ συνήνεικε πρῆγμα τοιόνδε ἰδόμενον ἐπιθυμῆσαι ἐντείλασθαι Μεγαβάζῳ Παίονας ἑλόντα ἀνασπάστους ποιῆσαι ἐκ τῆς Εὐρώπης ἐς τὴν Ἀσίην.

** ἔξεστι


Informação nova.

58. Herodotus - Historiae - 1 54
ἐξεῖναι τῷ βουλευομένῳ αὐτῶν γίνεσθαι Δελφὸν ἐς τὸν αἰεὶ χρόνον.

** παραγγέλλω


Informação nova, embora o assunto de pontes esteja ressoando.'

82. Herodotus - Historiae - 4 89
Δαρεῖος δὲ δωρησάμενος Μανδροκλέα διέβαινε ἐς τὴν Εὐρώπην, τοῖσι Ἴωσι παραγγείλας πλέειν ἐς τὸν Πόντον μέχρι Ἴστρου ποταμοῦ, ἐπεὰν δὲ ἀπίκωνται ἐς τὸν Ἴστρον, ἐνθαῦτα αὐτὸν περιμένειν, ζευγνύντας τὸν ποταμόν·


Informação nova.

83. Herodotus - Historiae - 6 78
Μαθὼν δὲ ὁ Κλεομένης ποιεῦντας τοὺς Ἀργείους ὁκοῖόν τι ὁ σφέτερος κῆρυξ σημήνειε, παραγγέλλει σφι, ὅταν σημήνῃ ὁ κῆρυξ ποιέεσθαι ἄριστον, τότε ἀναλαβόντας τὰ ὅπλα χωρέειν ἐς τοὺς Ἀργείους.


Informação nova.

84. Herodotus - Historiae - 9 53
Παυσανίης δὲ ὁρῶν σφέας ἀπαλλασσομένους ἐκ τοῦ στρατοπέδου παρήγγελλε καὶ τοῖσι Λακεδαιμονίοισι ἀναλαβόντας τὰ ὅπλα ἰέναι κατὰ τοὺς ἄλλους τοὺς προϊόντας, νομίσας αὐτοὺς ἐς τὸν χῶρον ἰέναι ἐς τὸν συνεθήκαντο.

** συμβουλεύω


Informação nova. Variação de aspecto em (d) e de raiz em (r), nada sobre caso.

100. Herodotus - Historiae - 2 107
Τὴν δέ οἱ συμβουλεῦσαι τῶν παίδων ἐόντων ἓξ τοὺς δύο ἐπὶ τὴν πυρὴν ἐκτείναντα γεφυρῶσαι τὸ καιόμενον, αὐτοὺς δ' ἐπ' ἐκείνων ἐπιβαίνοντας ἐκσῴζεσθαι


Informação nova.

101. Herodotus - Historiae - 7 120
ὃς συνεβούλευσε Ἀβδηρίτῃσι πανδημεὶ αὐτοὺς καὶ γυναῖκας, ἐλθόντας ἐς τὰ σφέτερα ἱρά, ἵζεσθαι ἱκέτας τῶν θεῶν παραιτεομένους καὶ τὸ λοιπόν σφι ἀπαμύνειν τῶν ἐπιόντων κακῶν τὰ ἡμίσεα, τῶν τε παροιχομένων ἔχειν σφι μεγάλην χάριν, ὅτι βασιλεὺς Ξέρξης οὐ δὶς ἑκάστης ἡμέρης ἐνόμισε σῖτον αἱρέεσθαι·


A adição dos ramos é essencial para a argumentação. Não há propriamente um efeito anafórico, mas de inversão daquilo que tinha sido feito antes. Há algum tipo de inversão de expectativa ou de eventos anteriores. Vou anotar como pressuposição, mas marcar.

102. Herodotus - Historiae - 7 141
Τίμων ὁ Ἀνδροβούλου, τῶν Δελφῶν ἀνὴρ δόκιμος ὅμοια τῷ μάλιστα, συνεβούλευέ σφι ἱκετηρίας λαβοῦσι δεύτερα αὖτις ἐλθόντας χρᾶσθαι τῷ χρηστηρίῳ ὡς ἱκέτας.


Informação nova.

103. Herodotus - Historiae - 7 173
ἀπικόμενοι γὰρ ἄγγελοι παρὰ Ἀλεξάνδρου τοῦ Ἀμύντεω ἀνδρὸς Μακεδόνος συνεβούλευόν σφι ἀπαλλάσσεσθαι μηδὲ μένοντας ἐν τῇ ἐσβολῇ καταπατηθῆναι ὑπὸ τοῦ στρατοῦ τοῦ ἐπιόντος, σημαίνοντες τὸ πλῆθός τε τῆς στρατιῆς καὶ τὰς νέας·


Informação nova.

106. Herodotus - Historiae - 1 53
τοὺς δὲ Ἑλλήνων δυνατωτάτους συνεβούλευόν οἱ ἐξευρόντα φίλους προσθέσθαι.

** ἐπισκήπτω


Informação nova.

Herodotus - Historiae - 4 33
οὕτω δὴ φέροντας ἐς τοὺς οὔρους τὰ ἱρὰ ἐνδεδεμένα ἐν πυρῶν καλάμῃ τοῖσι πλησιοχώροισι ἐπισκήπτειν κελεύοντας προπέμπειν σφέα ἀπὸ ἑωυτῶν ἐς ἄλλο ἔθνος.

** χρηίζω


Informação nova.

Herodotus - Historiae - 7 53
ὦ Πέρσαι, τῶνδ' ἐγὼ ὑμέων χρηίζων συνέλεξα, ἄνδρας τε γίνεσθαι ἀγαθοὺς καὶ μὴ καταισχύνειν τὰ πρόσθε ἐργασμένα Πέρσῃσι(...)

* Xenophon
** ἀφίημι

Pressuposição de que foi permitido ao falante "ir".

1. Xenophon - Hellenica - 6 1 13
ἀφῆκέ μοι ἐλθόντι πρὸς ὑμᾶς λέγειν τἀληθῆ

** δέομαι

Informação razoavelmente nova, difícil justificar o contrário.

4. Xenophon - Hellenica - 1 5 2
ἐνταῦθα δὴ κατά τε τοῦ Τισσαφέρνους ἔλεγον ἃ πεποιηκὼς εἴη, αὐτοῦ τε Κύρου ἐδέοντο ὡς προθυμοτάτου πρὸς τὸν πόλεμον γενέσθαι.

Pressupõe-se que o interlocutor saiba que vai juntar-se e assumir comando.

5. Xenophon - Anabasis - 6 6 33
δέονται δέ σου καὶ τοῦτο, παραγενόμενον καὶ ἄρξαντα ἑαυτῶν πεῖραν λαβεῖν καὶ Δεξίππου καὶ σφῶν τῶν ἄλλων οἷος ἕκαστός ἐστι, καὶ τὴν ἀξίαν ἑκάστοις νεῖμαι.


Informação nova.

6. Xenophon - Cyropaedia - 1 5 4
ἔπεμπε δὲ καὶ πρὸς Κῦρον, δεόμενος αὐτοῦ πειρᾶσθαι ἄρχοντα ἐλθεῖν τῶν ἀνδρῶν, εἴ τινας πέμποι στρατιώτας τὸ Περσῶν κοινόν.

Difícil argumentar algum pressuposição.

7. Xenophon - Cyropaedia - 7 2 23
ὑπὸ τῶν δεομένων μου προστάτην γενέσθαι.

** δοκεῖ

Informação nova.

25. Xenophon - Hellenica - 3 2 14
ἐπεὶ δ' ἐκεῖ ἦσαν, ἔδοξεν αὐτοῖς ἱκανὰς φυλακὰς εἰς τὰ ἐρύματα καταστήσαντας διαβαίνειν πάλιν ἐπὶ τὴν Ἰωνίαν.

Informação nova.

26. Xenophon - Hellenica - 3 5 23
διὰ οὖν πάντα ταῦτα ἔδοξεν αὐτοῖς τοὺς νεκροὺς ὑποσπόνδους ἀναιρεῖσθαι.

Informação nova.

27. Xenophon - Anabasis - 2 1 2
ἔδοξεν αὐτοῖς συσκευασαμένοις ἃ εἶχον καὶ ἐξοπλισαμένοις προϊέναι.

Informação nova.

28. Xenophon - Anabasis - 3 2 1
καὶ ἔδοξεν αὐτοῖς προφυλακὰς καταστήσαντας συγκαλεῖν τοὺς στρατιώτας.

Informação nova.

29. Xenophon - Anabasis - 4 1 12
ἅμα δὲ τῇ ἡμέρᾳ συνελθοῦσι τοῖς στρατηγοῖς καὶ λοχαγοῖς τῶν Ἑλλήνων ἔδοξε τῶν τε ὑποζυγίων τὰ ἀναγκαῖα καὶ δυνατώτατα ἔχοντας πορεύεσθαι, καταλιπόντας τἆλλα, καὶ ὅσα ἦν νεωστὶ αἰχμάλωτα ἀνδράποδα ἐν τῇ στρατιᾷ πάντα ἀφεῖναι.

Os generais haviam previamente decidido não fazer uma reunião antes do combate, logo é razoável assumir que συλλεγεῖσιν contradiz isso e assim pressuposição = t.

30. Xenophon - Anabasis - 4 8 9
ἔπειτα δὲ ἔδοξε τοῖς στρατηγοῖς βουλεύσασθαι συλλεγεῖσιν ὅπως ὡς κάλλιστα ἀγωνιοῦνται


Informação nova: conselho.

31. Xenophon - Anabasis - 4 8 12
ἀλλά μοι δοκεῖ ὀρθίους τοὺς λόχους ποιησαμένους τοσοῦτον χωρίον κατασχεῖν διαλιπόντας τοῖς λόχοις ὅσον ἔξω τοὺς ἐσχάτους λόχους γενέσθαι τῶν πολεμίων κεράτων·

A informação é nova, embora o contexto venha de 5.5.25.

32. Xenophon - Anabasis - 5 6 1
καὶ ἐδόκει αὐτοῖς περὶ τῆς λοιπῆς πορείας παρακαλέσαντας τοὺς Σινωπέας βουλεύεσθαι.

Informação pressuposta embora nova. Vide 6.6.29

33. Xenophon - Anabasis - 6 6 30
ἐκ τούτου ἔδοξεν αὐτοῖς πέμψαντας στρατηγοὺς καὶ λοχαγοὺς καὶ Δρακόντιον τὸν Σπαρτιάτην καὶ τῶν ἄλλων οἳ ἐδόκουν ἐπιτήδειοι εἶναι δεῖσθαι Κλεάνδρου κατὰ πάντα τρόπον ἀφεῖναι τὼ ἄνδρε.

Informação nova.

34. Xenophon - Anabasis - 6 6 38
ἔδοξεν αὐτοῖς τοὔμπαλιν ὑποστρέψαντας ἐλθεῖν μίαν ἡμέραν καὶ νύκτα.

Conselho, informação nova.

35. Xenophon - Anabasis - 7 1 31
καὶ νῦν μοι δοκεῖ πέμψαντας Ἀναξιβίῳ εἰπεῖν (...).


Informação pressuposta.

36. Xenophon - Cyropaedia - 3 3 14
ἡμῖν γὰρ δοκεῖ πᾶσιν, ἐπείπερ παρεσκευάσμεθα, μὴ ἐπειδὰν ἐμβάλωσιν οἱ πολέμιοι εἰς τὴν σὴν χώραν, τότε μάχεσθαι, μηδ' ἐν τῇ φιλίᾳ καθημένους ἡμᾶς ὑπομένειν, ἀλλ' ἰέναι ὡς τάχιστα εἰς τὴν πολεμίαν.

** ἐξαρκεῖ

A ideia de ver é parte essencial do presente discurso pela oposição entre ver *os deuses* e ver *o trabalho dos deuses*.

55. Xenophon - Memorabilia - 4 3 13
ἀλλ᾽ ἐξαρκῇ σοι τὰ ἔργα αὐτῶν ὁρῶντι σέβεσθαι καὶ τιμᾶν τοὺς θεούς.

** ἔξεστι

Catafórico: a informação do particípio ἑπομένῳ será invertida no próximo parágrafo.

59. Xenophon - Agesilaus - 2 12
ἐξὸν γὰρ αὐτῷ παρέντι τοὺς διαπίπτοντας ἑπομένῳ χειροῦσθαι τοὺς ὄπισθεν οὐκ ἐποίησε τοῦτο, ἀλλ' ἀντιμέτωπος συνέρραξε τοῖς Θηβαίοις.


Informação pressuposta: pergunta retórica.

60. Xenophon - Anabasis - 2 5 18
ἃ ἡμῖν ἔξεστι προκαταλαβοῦσιν ἄπορα ὑμῖν παρέχειν

Contrafactual: nesse momento, Xenofonte está acuado com que está acontecendo (7.1.18)

61. Xenophon - Anabasis - 7 1 21
νῦν σοι ἔξεστιν, ὦ Ξενοφῶν, ἀνδρὶ γενέσθαι

A ideia de pegar em armas iguais às dos persas está anunciada já em 2.1.13 para os interlocutores de Ciro.

62. Xenophon - Cyropaedia - 2 1 15
ἔξεστι δ' ὑμῖν, εἰ βούλεσθε, λαβόντας ὅπλα οἷάπερ ἡμεῖς ἔχομεν εἰς τὸν αὐτὸν ἡμῖν κίνδυνον ἐμβαίνειν, καὶ ἄν τι ἐκ τούτων καλὸν κἀγαθὸν γίγνηται, τῶν ὁμοίων ἡμῖν ἀξιοῦσθαι.


DEVE SER DELETADA
# 63. Xenophon - Cyropaedia - 7 2 14
# ἐξέσται δέ σοι ἰδόντι ταῦτα ἐλθόντα ἔτι καὶ περὶ τῆς ἁρπαγῆς βουλεύσασθαι.


Já fomos informados que Férulas desistiu de sua riqueza.

64. Xenophon - Cyropaedia - 8 3 50
οὕτω δὴ ὅτε Φεραύλας ὑπερήδετο ὅτι ἐξέσοιτο αὐτῷ ἀπαλλαγέντι τῆς τῶν ἄλλων κτημάτων ἐπιμελείας ἀμφὶ τοὺς φίλους ἔχειν, ὅ τε Σάκας ὅτι ἔμελλε πολλὰ ἔχων πολλοῖς χρήσεσθαι.


Xenofonte está apresentando as inovações legislativas de Licurgo, logo é de se esperar que um particípio antecedido por kai esteja apresentando uma prática social contraditória ao esperado pela audiência.

65. Xenophon - De republica Lacedaemoniorum - 13 9
ἔξεστι δὲ τῷ νέῳ καὶ κεχριμένῳ εἰς μάχην συνιέναι καὶ φαιδρὸν εἶναι καὶ εὐδοκιμεῖν.


A informação de "passar a viver entre nós" já estava pressuposta discursivamente, enquanto as demais não.

66. Xenophon - Hellenica - 4 1 35
νῦν δὲ ἔξεστί σοι μεθ' ἡμῶν γενομένῳ μηδένα προσκυνοῦντα μηδὲ δεσπότην ἔχοντα ζῆν καρπούμενον τὰ σαυτοῦ.

Conselho: informação nova.

67. Xenophon - Hellenica - 4 8 4
Ὦ ἄνδρες, νῦν ἔξεστιν ὑμῖν καὶ πρόσθεν φίλοις οὖσι τῇ πόλει ἡμῶν εὐεργέτας φανῆναι τῶν Λακεδαιμονίων.


Sphodrias enfrenta um processo com pena capital (5.4.24) e Xenofonte explica como ele se livrou nos próximos parágrafos.
É possível esperar que o pedido do pai seja que o filho peça ajuda a Archidamus, uma vez que já está dito que Archidamus tem Cleonymus em boa consideração.
No entanto, isso é pressuposto para Cleonymus?

68. Xenophon - Hellenica - 5 4 26
Ἔξεστί σοι, ὦ υἱέ, σῶσαι τὸν πατέρα, δεηθέντι Ἀρχιδάμου εὐμενῆ Ἀγησίλαον ἐμοὶ εἰς τὴν κρίσιν παρασχεῖν.


Informação nova na narrativa. 

69. Xenophon - Hellenica - 5 4 60
ἐξεῖναι γὰρ σφίσι ναῦς πληρώσαντας πολὺ πλείους τῶν Ἀθηναίων ἑλεῖν λιμῷ τὴν πόλιν αὐτῶν·


A cena implica que o leitor sabe que o polemarco lacedemônio tinha condições de disputar contra os tebanos e nos relata que a despeito disso ele decide não fazê-lo.
Pressuposição talvez não seja a palavra, mas há algum tipo de interação com fatos conhecidos e ações contrafactuais.

70. Xenophon - Hellenica - 7 1 17
(...) ἐξὸν τῷ Λακεδαιμονίων πολεμάρχῳ λαβόντι ὁπόσους μὲν ἐβούλετο τῶν συμμάχων ὁπλίτας, ὁπόσους δὲ πελταστάς, κατέχειν τὸ χωρίον, καὶ γὰρ τὰ ἐπιτήδεια ἐξῆν ἀσφαλῶς ἐκ Κεγχρειῶν κομίζεσθαι, οὐκ ἐποίησε ταῦτα (...)

Informação nova.

71. Xenophon - Hiero - 11 10
καὶ ἐξείη μὲν ἄν σοι ἕνεκεν ἀσφαλείας, εἴ ποι βούλοιο, θεωρήσοντι πορεύεσθαι, ἐξείη δ' ἂν αὐτοῦ μένοντι τοῦτο πράττειν

Informação nova.

72. Xenophon - Hiero - 6 11
ἐξῇ δ' αὐτοῖς ἐν ὀλίγῳ χρόνῳ πολὺ πλείω λαβεῖν ἀποκτείνασι τὸν τύραννον ἢ ὅσα πολὺν χρόνον φυλάττοντες παρὰ τοῦ τυράννου λαμβάνουσιν.

Informação nova.

73. Xenophon - Hipparchicus - 4 12
ἔτι δὲ τῷ μὲν κρυπτὰς ἔχοντι φυλακὰς ἐξέσται μὲν φανεροῖς ὀλίγοις ἔμπροσθεν τῶν κρυπτῶν φυλάττοντα πειρᾶσθαι τοὺς πολεμίους εἰς ἐνέδρας ὑπάγειν·

διαπονησαμένῳ se refere a uma série de ações descritas anteriormente.

74. Xenophon - Memorabilia - 2 1 33
τοιαῦτά σοι, ὦ παῖ τοκέων ἀγαθῶν Ἡράκλεις, ἔξεστι διαπονησαμένῳ τὴν μακαριστοτάτην εὐδαιμονίαν κεκτῆσθαι.


O tópico da discussão é o fato do falante estar elogiando seu coelocutor.

75. Xenophon - Memorabilia - 2 6 36
ἃ δὴ καὶ ἐγὼ πεισθεὶς ὀρθῶς ἔχειν ἡγοῦμαι οὐκ ἐξεῖναί μοι περὶ σοῦ λέγειν ἐπαινοῦντι οὐδὲν ὅ τι ἂν μὴ ἀληθεύω.

A discussão revolve o tipo de ações, logo pressuposto.

76. Xenophon - Memorabilia - 3 9 9
ἐξεῖναι γὰρ αὐτοῖς ἰέναι πράξοντας τὰ βελτίω τούτων.

Figura contraditória ao homem virtuoso.

77. Xenophon - Memorabilia - 4 5 10
τῷ γὰρ ἂν ἧττον φήσαιμεν τῶν τοιούτων προσήκειν, ἢ ᾧ ἥκιστα ἔξεστι ταῦτα πράττειν κατεχομένῳ ἐπὶ τῷ σπουδάζειν περὶ τὰς ἐγγυτάτω ἡδονάς;

Informação nova.

78. Xenophon - Memorabilia - 4 5 11
ἀλλὰ τοῖς ἐγκρατέσι μόνοις ἔξεστι σκοπεῖν τὰ κράτιστα τῶν πραγμάτων, καὶ λόγῳ καὶ ἔργῳ διαλέγοντας κατὰ γένη τὰ μὲν ἀγαθὰ προαιρεῖσθαι, τῶν δὲ κακῶν ἀπέχεσθαι.

** παραγγέλλω

Os particípios comentam sobre uma informação já conhecida sobre Clearco e Aristipo.

85. Xenophon - Anabasis - 1 2 1
ἐνταῦθα καὶ παραγγέλλει τῷ τε Κλεάρχῳ λαβόντι ἥκειν ὅσον ἦν αὐτῷ στράτευμα καὶ τῷ Ἀριστίππῳ συναλλαγέντι πρὸς τοὺς οἴκοι ἀποπέμψαι πρὸς ἑαυτὸν ὃ εἶχε στράτευμα


Xenias está sendo aprensentado apenas agora.

86. Xenophon - Anabasis - 1 2 1
καὶ Ξενίᾳ τῷ Ἀρκάδι, ὃς αὐτῷ προειστήκει τοῦ ἐν ταῖς πόλεσι ξενικοῦ, ἥκειν παραγγέλλει λαβόντα τοὺς ἄλλους πλὴν ὁπόσοι ἱκανοὶ ἦσαν τὰς ἀκροπόλεις φυλάττειν.

Informação nova.

87. Xenophon - Anabasis - 4 3 26
καὶ παρήγγειλε τοῖς λοχαγοῖς κατ' ἐνωμοτίας ποιήσασθαι ἕκαστον τὸν ἑαυτοῦ λόχον, παρ' ἀσπίδα παραγαγόντας τὴν ἐνωμοτίαν ἐπὶ φάλαγγος·

Informação nova.

88. Xenophon - Anabasis - 4 3 29
τοῖς δὲ παρ' ἑαυτῷ παρήγγειλεν, ἐπειδὰν σφενδόνη ἐξικνῆται καὶ ἀσπὶς ψοφῇ, παιανίσαντας θεῖν εἰς τοὺς πολεμίους, ἐπειδὰν δ' ἀναστρέψωσιν οἱ πολέμιοι καὶ ἐκ τοῦ ποταμοῦ ὁ σαλπικτὴς σημήνῃ τὸ πολεμικόν, ἀναστρέψαντας ἐπὶ δόρυ ἡγεῖσθαι μὲν τοὺς οὐραγούς, θεῖν δὲ πάντας καὶ διαβαίνειν ὅτι τάχιστα ᾗ ἕκαστος τὴν τάξιν εἶχεν, ὡς μὴ ἐμποδίζειν ἀλλήλους·

Informação nova.

89. Xenophon - Anabasis - 5 2 12
ὁ δὲ τοῖς πελτασταῖς πᾶσι παρήγγειλε διηγκυλωμένους ἰέναι, ὡς, ὁπόταν σημήνῃ, ἀκοντίζειν, καὶ τοὺς τοξότας ἐπιβεβλῆσθαι ἐπὶ ταῖς νευραῖς, ὡς, ὁπόταν σημήνῃ, τοξεύειν δεῆσον, καὶ τοὺς γυμνῆτας λίθων ἔχειν μεστὰς τὰς διφθέρας·


Informação nova.

90. Xenophon - Cyropaedia - 2 4 2
ἀκούσας δὲ ταῦτα ὁ Κῦρος παρήγγειλε τῷ πρώτῳ τεταγμένῳ ταξιάρχῳ εἰς μέτωπον στῆναι, ἐφ' ἑνὸς ἄγοντα τὴν τάξιν, ἐν δεξιᾷ ἔχοντα ἑαυτόν, καὶ τῷ δευτέρῳ ἐκέλευσε ταὐτὸ τοῦτο παραγγεῖλαι, καὶ διὰ πάντων οὕτω παραδιδόναι ἐκέλευσεν.


Repetição de ἐστεφανωμένος - ἐστεφανωμένοις. Há questões culturais que não sei confirmar: esperava-se que só Ciro usasse coroa?

91. Xenophon - Cyropaedia - 3 3 34
τῇ δ' ὑστεραίᾳ πρῲ Κῦρος μὲν ἐστεφανωμένος ἔθυε, παρήγγειλε δὲ καὶ τοῖς ἄλλοις ὁμοτίμοις ἐστεφανωμένοις πρὸς τὰ ἱερὰ παρεῖναι.


Informação nova.

92. Xenophon - Cyropaedia - 6 3 21
παραγγείλατε δὲ τοῖς ταξιάρχοις καὶ λοχαγοῖς ἐπὶ φάλαγγος καθίστασθαι εἰς δύο ἔχοντας ἕκαστον τὸν λόχον.


Informação nova.

93. Xenophon - Hellenica - 1 6 37
καὶ οἱ μὲν τοῦτ' ἐποίουν· αὐτὸς δ', ἐπειδὴ ἐκεῖνοι κατέπλεον, ἔθυε τὰ εὐαγγέλια, καὶ τοῖς στρατιώταις παρήγγειλε δειπνοποιεῖσθαι, καὶ τοῖς ἐμπόροις τὰ χρήματα σιωπῇ ἐνθεμένους εἰς τὰ πλοῖα ἀποπλεῖν εἰς Χίον (ἦν δὲ τὸ πνεῦμα οὔριον) καὶ τὰς τριήρεις τὴν ταχίστην.

** προσήκει

Informação relativamente nova, o discursso ainda não havia falado de virtudes como "coragem".

94. Xenophon - Anabasis - 3 2 11
ἵνα εἰδῆτε ὡς ἀγαθοῖς τε ὑμῖν προσήκει εἶναι σῴζονταί τε σὺν τοῖς θεοῖς καὶ ἐκ πάνυ δεινῶν οἱ ἀγαθοί.

Recupera o capítulo anterior.

95. Xenophon - Hipparchicus - 7 1
παντὶ μὲν οὖν προσήκει ἄρχοντι φρονίμῳ εἶναι.

** συμβουλεύω


Conselho, informação nova. Alguém poderia, no entanto, argumentar que é pressuposto culturalmente que seja feita uma viagem para consultar o oráculo.

104. Xenophon - Anabasis - 3 1 5
συμβουλεύει τῷ Ξενοφῶντι ἐλθόντα εἰς Δελφοὺς ἀνακοινῶσαι τῷ θεῷ περὶ τῆς πορείας.

Informação nova.

105. Xenophon - Anabasis - 7 1 30
καὶ ὑμῖν δὲ συμβουλεύω Ἕλληνας ὄντας τοῖς τῶν Ἑλλήνων προεστηκόσι πειθομένους πειρᾶσθαι τῶν δικαίων τυγχάνειν.

Informação nova.

107. Xenophon - Cyropaedia - 4 5 32
συμβουλεύω δέ σοι καίπερ νεώτερος ὢν μὴ ἀφαιρεῖσθαι ἃ ἂν δῷς, ἵνα μή σοι ἀντὶ χαρίτων ἔχθραι ὀφείλωνται, μηδ' ὅταν τινὰ βούλῃ πρὸς σὲ ταχὺ ἐλθεῖν, ἀπειλοῦντα μεταπέμπεσθαι, μηδὲ φάσκοντα ἔρημον εἶναι ἅμα πολλοῖς ἀπειλεῖν, ἵνα μὴ διδάσκῃς αὐτοὺς σοῦ μὴ φροντίζειν.

Informação nova.

108. Xenophon - Hipparchicus - 1 18
συγκαλέσαντα δὲ χρὴ τοὺς ἱππέας συμβουλεῦσαι αὐτοῖς μελετᾶν, καὶ ὅταν εἰς χώραν ἐλαύνωσι καὶ ὅταν ἄλλοσέ ποι, ἐκβιβάζοντας τῶν ὁδῶν καὶ ταχὺ ἐλαύνοντας ἐν τόποις παντοδαποῖς.

Informação já data, tema do capítulo.

109. Xenophon - Memorabilia - 1 3 6
τοῖς δὲ μὴ δυναμένοις τοῦτο ποιεῖν συνεβούλευε φυλάττεσθαι τὰ πείθοντα μὴ πεινῶντας ἐσθίειν μηδὲ διψῶντας πίνειν·

** δίδωμι

Contra-parte ao que foi dito nos parágrafos anteriores.

113. Xenophon - Cyropaedia - 6 4 9
ὦ Ζεῦ μέγιστε, δός μοι φανῆναι ἀξίῳ μὲν Πανθείας ἀνδρί, ἀξίῳ δὲ Κύρου φίλῳ

** συμφέρει

Informação nova.

122. Xenophon - Oeconomicus - 11 23 7
ὡς συμφέρει αὐτοῖς φίλους εἶναι μᾶλλον ἢ πολεμίους

* Plato

** TODO δοκεῖ
    37. Plato - Phaedo - 86 d
    δοκεῖ μέντοι μοι χρῆναι πρὸ τῆς ἀποκρίσεως ἔτι πρότερον Κέβητος ἀκοῦσαι τί αὖ ὅδε ἐγκαλεῖ τῷ λόγῳ, ἵνα χρόνου ἐγγενομένου βουλευσώμεθα τί ἐροῦμεν, ἔπειτα δὲ ἀκούσαντας ἢ συγχωρεῖν αὐτοῖς ἐάν τι δοκῶσι προσᾴδειν, ἐὰν δὲ μή, οὕτως ἤδη ὑπερδικεῖν τοῦ λόγου.

    38. Plato - Phaedo - 98 e
    ἐπειδὴ Ἀθηναίοις ἔδοξε βέλτιον εἶναι ἐμοῦ καταψηφίσασθαι, διὰ ταῦτα δὴ καὶ ἐμοὶ βέλτιον αὖ δέδοκται ἐνθάδε καθῆσθαι, καὶ δικαιότερον παραμένοντα ὑπέχειν τὴν δίκην ἣν ἂν κελεύσωσιν·

    39. Plato - Phaedo - 99 e
    ἔδοξε δή μοι χρῆναι εἰς τοὺς λόγους καταφυγόντα ἐν ἐκείνοις σκοπεῖν τῶν ὄντων τὴν ἀλήθειαν.

    40. Plato - Symposium - 185 e
    Δοκεῖ τοίνυν μοι ἀναγκαῖον εἶναι, ἐπειδὴ Παυσανίας ὁρμήσας ἐπὶ τὸν λόγον καλῶς οὐχ ἱκανῶς ἀπετέλεσε, δεῖν ἐμὲ πειρᾶσθαι τέλος ἐπιθεῖναι τῷ λόγῳ.

    41. Plato - Laches - 181 d
    δικαιότατον μέντοι μοι δοκεῖ εἶναι ἐμὲ νεώτερον ὄντα τῶνδε καὶ ἀπειρότερον τούτων ἀκούειν πρότερον τί λέγουσιν καὶ μανθάνειν παρ' αὐτῶν·

    42. Plato - Lysis - 213 e
    ᾗ δὲ ἐτράπημεν, δοκεῖ μοι χρῆναι ἰέναι, σκοποῦντα τὰ κατὰ τοὺς ποιητάς·

    43. Plato - Menexenus - 239 c
    τούτων πέρι μοι δοκεῖ χρῆναι ἐπιμνησθῆναι ἐπαινοῦντά τε καὶ προμνώμενον ἄλλοις ἐς ᾠδάς τε καὶ τὴν ἄλλην ποίησιν αὐτὰ θεῖναι πρεπόντως τῶν πραξάντων

    44. Plato - Respublica - 578 d
    δοκεῖ γάρ μοι δεῖν ἐννοῆσαι ἐκ τῶνδε περὶ αὐτοῦ σκοποῦντας.

    45. Plato - Leges - 683 d
    τὸ δὲ δὴ μετὰ τοῦτο ἔδοξεν αὐτοῖς, ὥς γε λέγεται τὸ τοῦ μύθου, τριχῇ τὸ στράτευμα διανείμαντας, τρεῖς πόλεις κατοικίζειν, Ἄργος, Μεσσήνην, Λακεδαίμονα.

** TODO ἐγχωρεῖ
46. Plato - Protagoras - 344 e
τῷ μὲν γὰρ ἐσθλῷ ἐγχωρεῖ κακῷ γενέσθαι.

47. Plato - Respublica - 408 e
ἀλλὰ ψυχῇ σῶμα, ᾗ οὐκ ἐγχωρεῖ κακὴν γενομένην τε καὶ οὖσαν εὖ τι θεραπεύειν.

** TODO ἐξαρκεῖ
56. Plato - Symposium - 192 b
ἀλλ᾽ ἐξαρκεῖ αὐτοῖς μετ᾽ ἀλλήλων καταζῆν ἀγάμοις.

57. Plato - Respublica - 341 e
ὥσπερ, ἔφην ἐγώ, εἴ με ἔροιο εἰ ἐξαρκεῖ σώματι εἶναι σώματι ἢ προσδεῖταί τινος, εἴποιμ᾽ ἂν ὅτι ‘παντάπασι μὲν οὖν προσδεῖται. διὰ ταῦτα καὶ ἡ τέχνη ἐστὶν ἡ ἰατρικὴ νῦν ηὑρημένη, ὅτι σῶμά ἐστιν πονηρὸν καὶ οὐκ ἐξαρκεῖ αὐτῷ τοιούτῳ εἶναι.

** TODO ἔξεστι
78. Plato - Protagoras - 350 e.4
ταῦτα δὲ ἐμοῦ ὁμολογήσαντος ἐξείη ἄν σοι, χρωμένῳ τοῖς αὐτοῖς τεκμηρίοις τούτοις, λέγειν ὡς κατὰ τὴν ἐμὴν ὁμολογίαν ἡ σοφία ἐστὶν ἰσχύς.

79. Plato - Respublica - 360b.6
ἐξὸν αὐτῷ καὶ ἐκ τῆς ἀγορᾶς ἀδεῶς ὅτι βούλοιτο λαμβάνειν, καὶ εἰσιόντι εἰς τὰς οἰκίας συγγίγνεσθαι ὅτῳ βούλοιτο, καὶ ἀποκτεινύναι καὶ ἐκ δεσμῶν λύειν οὕστινας βούλοιτο, καὶ τἆλλα πράττεινἐν τοῖς ἀνθρώποις ἰσόθεον ὄντα.

80. Plato - Respublica - 422 b.10
Οὐδ' εἰ ἐξείη, ἦν δ' ἐγώ, ὑποφεύγοντι τὸν πρότερον ἀεὶ προσφερόμενον ἀναστρέφοντα κρούειν, καὶ τοῦτο ποιοῖ πολλάκις ἐν ἡλίῳ τε καὶ πνίγει;

** TODO προσήκει
95. Plato - Gorgias - 525 b
προσήκει δὲ παντὶ τῷ ἐν τιμωρίᾳ ὄντι, ὑπ᾽ ἄλλου ὀρθῶς τιμωρουμένῳ, ἢ βελτίονι γίγνεσθαι καὶ ὀνίνασθαι ἢ παραδείγματι τοῖς ἄλλοις γίγνεσθαι (...)

96. Plato - Parmenides - 139 c
ἕτερον δέ γε ἑτέρου οὐκ ἔσται, ἕως ἂν ᾖ ἕν: οὐ γὰρ ἑνὶ προσήκει ἑτέρῳ τινὸς εἶναι, ἀλλὰ μόνῳ ἑτέρῳ ἑτέρου, ἄλλῳ δὲ οὐδενί.

97. Plato - Phaedo - 80 b
τί οὖν; τούτων οὕτως ἐχόντων ἆρ᾽ οὐχὶ σώματι μὲν ταχὺ διαλύεσθαι προσήκει, ψυχῇ δὲ αὖ τὸ παράπαν ἀδιαλύτῳ εἶναι ἢ ἐγγύς τι τούτου;

98. Plato - Politicus - 311 c
καὶ καθ᾽ ὅσον εὐδαίμονι προσήκει γίγνεσθαι πόλει (...)

114. Plato - Phaedrus - 233 a
καὶ μὲν δὴ βελτίονί σοι προσήκει γενέσθαι ἐμοὶ πειθομένῳ ἢ ἐραστῇ.

115. Plato - Gorgias - 485 b
ὅταν μὲν γὰρ παιδίον ἴδω, ᾧ ἔτι προσήκει διαλέγεσθαι οὕτω, ψελλιζόμενον καὶ παῖζον, χαίρω (...)

116. Plato - Respublica - 441 e
Οὐκοῦν τῷ μὲν λογιστικῷ ἄρχειν προσήκει, σοφῷ ὄντι καὶ ἔχοντι τὴν ὑπὲρ ἁπάσης τῆς ψυχῆς προμήθειαν, τῷ δὲ θυμοειδεῖ ὑπηκόῳ εἶναι καὶ συμμάχῳ τούτου;

117. Plato - Leges - 758 c
(...) ἄντε ἀγγέλλειν βούληταί τις ἐάντ' αὖ πυνθάνεσθαί τι τῶν ὧν προσήκει πόλει πρὸς πόλεις ἄλλας ἀποκρίνεσθαί τε, καὶ ἐρωτήσασαν ἑτέρας, ἀποδέξασθαι τὰς ἀποκρίσεις (...)

118. Plato - Timaeus - 29 b
καθ' ὅσον οἷόν τε καὶ ἀνελέγκτοις προσήκει λόγοις εἶναι καὶ ἀνικήτοις

119. Plato - Timaeus - 41 c
καὶ καθ' ὅσον μὲν αὐτῶν ἀθανάτοις ὁμώνυμον εἶναι προσήκει

** TODO συμβουλεύω
109. Plato - Charmides - 176a3
ἀλλ' ὅρα εἰ ἔχεις τε καὶ μηδὲν δέῃ τῆς ἐπῳδῆς· εἰ γὰρ ἔχεις, μᾶλλον ἂν ἔγωγέ σοι συμβουλεύσαιμι ἐμὲ μὲν λῆρον ἡγεῖσθαι εἶναι καὶ ἀδύνατον λόγῳ ὁτιοῦν ζητεῖν, σεαυτὸν δέ, ὅσῳπερ σωφρονέστερος εἶ, τοσούτῳ εἶναι καὶ εὐδαιμονέστερον.

110. Plato - Respublica - 390 e
οὐδὲ τὸν τοῦ Ἀχιλλέως παιδαγωγὸν Φοίνικα ἐπαινετέον ὡς μετρίως ἔλεγε συμβουλεύων αὐτῷ δῶρα μὲν λαβόντι ἐπαμύνειν τοῖς Ἀχαιοῖς, ἄνευ δὲ δώρων μὴ ἀπαλλάττεσθαι τῆς μήνιος.

** TODO ὑπάρχει
111. Plato - Phaedo - 81 a
οἷ ἀφικομένῃ ὑπάρχει αὐτῇ εὐδαίμονι εἶναι

** TODO συμφέρει
122. Plato - Respublica - 344 a
τοῦτον οὖν σκόπει, εἴπερ βούλει κρίνειν ὅσῳ μᾶλλον συμφέρει ἰδίᾳ αὑτῷ ἄδικον εἶναι ἢ τὸ δίκαιον.
